//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_message
    {
        public int ID { get; set; }
        public int 类型 { get; set; }
        public string 设备 { get; set; }
        public string 设备_地址 { get; set; }
        public string 设备_具体地址 { get; set; }
        public string 位触发条件 { get; set; }
        public string 字触发条件 { get; set; }
        public string 字触发条件_具体 { get; set; }
        public string 报警内容 { get; set; }
    }
}
