//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageButton_Class
    {
        public string ID { get; set; }
        public string FORM { get; set; }
        public string 位指示灯 { get; set; }
        public string 位切换开关 { get; set; }
        public string 读写设备 { get; set; }
        public string 读写设备_地址 { get; set; }
        public string 读写设备_地址_具体地址 { get; set; }
        public int 读写不同地址_ON_OFF { get; set; }
        public string 写设备_复选 { get; set; }
        public string 写设备_地址_复选 { get; set; }
        public string 写设备_地址_具体地址_复选 { get; set; }
        public string 操作模式 { get; set; }
        public string 操作安全时间 { get; set; }
        public string Control_type { get; set; }
        public int Control_state_0 { get; set; }
        public string Control_state_0_typeface { get; set; }
        public string Control_state_0_colour { get; set; }
        public string Control_state_0_size { get; set; }
        public string Control_state_0_aligning { get; set; }
        public string Control_state_0_content { get; set; }
        public int Control_state_0_flicker { get; set; }
        public int Control_state_1 { get; set; }
        public string Control_state_1_typeface { get; set; }
        public string Control_state_1_colour { get; set; }
        public string Control_state_1_size { get; set; }
        public string Control_state_1_aligning { get; set; }
        public string Control_state_1_content1 { get; set; }
        public int Control_state_1_flicker { get; set; }
        public string location { get; set; }
        public string size { get; set; }
    }
}
