//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UppercomputerEntities2 : DbContext
    {
        public UppercomputerEntities2()
            : base("name=UppercomputerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalogMeter_parameter> AnalogMeter_parameter { get; set; }
        public virtual DbSet<Button_colour> Button_colour { get; set; }
        public virtual DbSet<Button_parameter> Button_parameter { get; set; }
        public virtual DbSet<Control_layer> Control_layer { get; set; }
        public virtual DbSet<control_location> control_location { get; set; }
        public virtual DbSet<doughnut_Chart_parameter> doughnut_Chart_parameter { get; set; }
        public virtual DbSet<Event_message> Event_message { get; set; }
        public virtual DbSet<function_key_parameter> function_key_parameter { get; set; }
        public virtual DbSet<General_parameters_of_picture> General_parameters_of_picture { get; set; }
        public virtual DbSet<GroupBox_parameter> GroupBox_parameter { get; set; }
        public virtual DbSet<histogram_Chart_parameter> histogram_Chart_parameter { get; set; }
        public virtual DbSet<HScrollBar_parameter> HScrollBar_parameter { get; set; }
        public virtual DbSet<ihatetheqrcode_parameter> ihatetheqrcode_parameter { get; set; }
        public virtual DbSet<ImageButton_parameter> ImageButton_parameter { get; set; }
        public virtual DbSet<label_parameter> label_parameter { get; set; }
        public virtual DbSet<LedBulb_parameter> LedBulb_parameter { get; set; }
        public virtual DbSet<LedDisplay_parameter> LedDisplay_parameter { get; set; }
        public virtual DbSet<numerical_parameter> numerical_parameter { get; set; }
        public virtual DbSet<oscillogram_Chart_parameter> oscillogram_Chart_parameter { get; set; }
        public virtual DbSet<picture_parameter> picture_parameter { get; set; }
        public virtual DbSet<PLC_macroinstruction> PLC_macroinstruction { get; set; }
        public virtual DbSet<PLC_parameter> PLC_parameter { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<pull_down_menu_parameter> pull_down_menu_parameter { get; set; }
        public virtual DbSet<pull_down_menuName> pull_down_menuName { get; set; }
        public virtual DbSet<RadioButton_parameter> RadioButton_parameter { get; set; }
        public virtual DbSet<ScrollingText_parameter> ScrollingText_parameter { get; set; }
        public virtual DbSet<Switch_parameter> Switch_parameter { get; set; }
        public virtual DbSet<Tag_common_parameters> Tag_common_parameters { get; set; }
        public virtual DbSet<AnalogMeter_Class> AnalogMeter_Class { get; set; }
        public virtual DbSet<Button_Class> Button_Class { get; set; }
        public virtual DbSet<doughnut_Chart_Class> doughnut_Chart_Class { get; set; }
        public virtual DbSet<function_key_Class> function_key_Class { get; set; }
        public virtual DbSet<GroupBox_Class> GroupBox_Class { get; set; }
        public virtual DbSet<histogram_Chart_Class> histogram_Chart_Class { get; set; }
        public virtual DbSet<HScrollBar_Class> HScrollBar_Class { get; set; }
        public virtual DbSet<ihatetheqrcode_Class> ihatetheqrcode_Class { get; set; }
        public virtual DbSet<ImageButton_Class> ImageButton_Class { get; set; }
        public virtual DbSet<label_Class> label_Class { get; set; }
        public virtual DbSet<LedBulb_Class> LedBulb_Class { get; set; }
        public virtual DbSet<LedDisplay_Class> LedDisplay_Class { get; set; }
        public virtual DbSet<numerical_Class> numerical_Class { get; set; }
        public virtual DbSet<oscillogram_Chart_Class> oscillogram_Chart_Class { get; set; }
        public virtual DbSet<picture_Class> picture_Class { get; set; }
        public virtual DbSet<pull_down_menu_Class> pull_down_menu_Class { get; set; }
        public virtual DbSet<RadioButton_Class> RadioButton_Class { get; set; }
        public virtual DbSet<ScrollingText_Class> ScrollingText_Class { get; set; }
        public virtual DbSet<Switch_Class> Switch_Class { get; set; }
    }
}
