//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class numerical_parameter
    {
        public string ID { get; set; }
        public string FORM { get; set; }
        public string 读写设备 { get; set; }
        public string 读写设备_地址 { get; set; }
        public string 读写设备_地址_具体地址 { get; set; }
        public int 读写不同地址_ON_OFF { get; set; }
        public string 写设备_复选 { get; set; }
        public string 写设备_地址_复选 { get; set; }
        public string 写设备_地址_具体地址_复选 { get; set; }
        public string 资料格式 { get; set; }
        public string 数据类型 { get; set; }
        public string 小数点以上位数 { get; set; }
        public string 小数点以下位数 { get; set; }
        public string 操作安全时间 { get; set; }
    }
}
