//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLC_parameter
    {
        public int ID { get; set; }
        public string 三菱PLC_IP { get; set; }
        public string 三菱PLC_端口 { get; set; }
        public string 三菱PLC_类型 { get; set; }
        public string 三菱PLC_链接类型 { get; set; }
        public string 西门子PLC_IP { get; set; }
        public string 西门子PLC_端口 { get; set; }
        public string 西门子PLC_类型 { get; set; }
        public string 西门子PLC_链接类型 { get; set; }
        public string MODBUS_TCP_PLC_IP { get; set; }
        public string MODBUS_TCP_PLC_端口11 { get; set; }
        public string MODBUS_TCP_PLC_类型 { get; set; }
        public string MODBUS_TCP_PLC_链接类型 { get; set; }
    }
}
