//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLC_macroinstruction
    {
        public int ID { get; set; }
        public int 方法索引 { get; set; }
        public string 宏指令名称 { get; set; }
        public int 运行时间间隔 { get; set; }
        public bool 是否周期执行 { get; set; }
        public string 内容 { get; set; }
    }
}
