//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class pull_down_menuName
    {
        public string ID { get; set; }
        public string FORM { get; set; }
        public int 项目 { get; set; }
        public string 数据 { get; set; }
        public string 项目资料 { get; set; }
        public string 控件归属 { get; set; }
    }
}
