//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 自定义Uppercomputer_20200727.EF实体模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_common_parameters
    {
        public string ID { get; set; }
        public string FROM { get; set; }
        public string Control_type { get; set; }
        public int Control_state_0 { get; set; }
        public string Control_state_0_typeface { get; set; }
        public string Control_state_0_colour { get; set; }
        public string Control_state_0_size { get; set; }
        public string Control_state_0_aligning { get; set; }
        public string Control_state_0_content { get; set; }
        public int Control_state_0_flicker { get; set; }
        public int Control_state_1 { get; set; }
        public string Control_state_1_typeface { get; set; }
        public string Control_state_1_colour { get; set; }
        public string Control_state_1_size { get; set; }
        public string Control_state_1_aligning { get; set; }
        public string Control_state_1_content1 { get; set; }
        public int Control_state_1_flicker { get; set; }
    }
}
